"""
PersonaScriptArchitectureAgent - Technical architecture design, AI model selection,
and data security protocols agent for PersonaScript.

This agent parses requirements, evaluates AI models, designs AWS-based system architecture,
establishes data security & compliance protocols, and outputs links to a Miro diagram,
Google Docs security compliance plan, and GitHub tracking issue.
"""

import os
import logging
from typing import Dict, List, Optional, Any
from dataclasses import dataclass, field
from datetime import datetime, timezone

from ..integrations.miro_integration import MiroIntegration
from ..integrations.google_docs_integration import GoogleDocsIntegration
from ..integrations.github_integration import GitHubIntegration

logger = logging.getLogger(__name__)


@dataclass
class ArchitectureInputs:
    """Inputs for the PersonaScriptArchitectureAgent."""

    business_requirements: str
    value_proposition: str
    existing_infrastructure: Optional[str] = None
    compliance_standards: List[str] = field(
        default_factory=lambda: ["GDPR", "SOC 2 Type II"]
    )


@dataclass
class ArchitectureOutputs:
    """Outputs generated by the PersonaScriptArchitectureAgent."""

    miro_diagram_url: str
    security_plan_doc_url: str
    github_issue_url: str
    selected_ai_models: List[Dict[str, Any]]
    system_architecture_summary: Dict[str, Any]
    security_compliance_summary: Dict[str, Any]
    status: str = "success"
    error_message: Optional[str] = None


class PersonaScriptArchitectureAgent:
    """
    Agent responsible for finalizing technical architecture design,
    AI model selection, and data security protocols for PersonaScript.

    Follows an 8-step execution plan:
    1. Parse requirements and value proposition for functional/non-functional needs.
    2. Research & evaluate suitable AI models for hyper-personalized, high-volume generation.
    3. Design high-level system architecture using AWS components.
    4. Develop comprehensive data security protocols.
    5. Outline detailed security compliance plan for GDPR and SOC 2.
    6. Create detailed system architecture diagram in Miro.
    7. Generate comprehensive security compliance plan document in Google Docs.
    8. Construct detailed GitHub issue detailing all decisions and links.
    """

    def __init__(
        self,
        miro_api_key: Optional[str] = None,
        google_docs_credentials: Optional[Dict[str, Any]] = None,
        github_token: Optional[str] = None,
        github_repo: Optional[str] = None
    ):
        """Initialize the PersonaScriptArchitectureAgent with necessary integrations."""
        self.miro_integration = MiroIntegration(api_key=miro_api_key)
        self.google_docs_integration = GoogleDocsIntegration(credentials=google_docs_credentials)
        self.github_integration = GitHubIntegration(
            token=github_token or os.environ.get("GITHUB_TOKEN"),
            repo=github_repo or os.environ.get("GITHUB_REPO", "groupthinking/personascript")
        )
        self.execution_log: List[Dict[str, Any]] = []
        logger.info("PersonaScriptArchitectureAgent initialized.")

    def _log_step(self, step_number: int, description: str, status: str = "started", data: Optional[Dict[str, Any]] = None):
        """Log execution step into self.execution_log."""
        log_entry = {
            "step": step_number,
            "description": description,
            "status": status,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "data": data or {}
        }
        self.execution_log.append(log_entry)
        logger.info(f"Step {step_number}: {description} - {status}")

    def execute(self, inputs: ArchitectureInputs) -> ArchitectureOutputs:
        """
        Execute the complete 8-step architecture and security compliance workflow.
        """
        logger.info("Starting PersonaScriptArchitectureAgent execution.")
        self.execution_log = []

        try:
            # Step 1: Parse requirements and value proposition
            self._log_step(1, "Parse requirements and value proposition")
            parsed_needs = self._parse_requirements(inputs)
            self._log_step(1, "Parse requirements and value proposition", "completed", parsed_needs)

            # Step 2: Research and evaluate AI models
            self._log_step(2, "Research and evaluate AI models")
            selected_models = self._evaluate_ai_models(parsed_needs)
            self._log_step(2, "Research and evaluate AI models", "completed", {"selected_models_count": len(selected_models)})

            # Step 3: Design high-level system architecture using AWS components
            self._log_step(3, "Design high-level AWS architecture")
            architecture_design = self._design_aws_architecture(parsed_needs, selected_models)
            self._log_step(3, "Design high-level AWS architecture", "completed")

            # Step 4: Develop comprehensive data security protocols
            self._log_step(4, "Develop data security protocols")
            security_protocols = self._develop_security_protocols()
            self._log_step(4, "Develop data security protocols", "completed")

            # Step 5: Outline security compliance plan for GDPR and SOC 2
            self._log_step(5, "Outline security compliance plan")
            compliance_plan = self._outline_compliance_plan(inputs.compliance_standards, security_protocols)
            self._log_step(5, "Outline security compliance plan", "completed")

            # Step 6: Create system architecture diagram in Miro
            self._log_step(6, "Create Miro architecture diagram")
            miro_url = self._create_miro_diagram(architecture_design, selected_models, security_protocols)
            self._log_step(6, "Create Miro architecture diagram", "completed", {"miro_url": miro_url})

            # Step 7: Generate security compliance plan document
            self._log_step(7, "Generate security compliance plan document")
            doc_url = self._generate_compliance_doc(compliance_plan, security_protocols)
            self._log_step(7, "Generate security compliance plan document", "completed", {"doc_url": doc_url})

            # Step 8: Construct detailed GitHub issue
            self._log_step(8, "Construct detailed GitHub issue")
            github_issue_url = self._create_github_issue(
                inputs=inputs,
                miro_url=miro_url,
                doc_url=doc_url,
                selected_models=selected_models,
                architecture_design=architecture_design,
                security_protocols=security_protocols,
                compliance_plan=compliance_plan
            )
            self._log_step(8, "Construct detailed GitHub issue", "completed", {"github_issue_url": github_issue_url})

            logger.info("PersonaScriptArchitectureAgent execution completed successfully.")
            return ArchitectureOutputs(
                miro_diagram_url=miro_url,
                security_plan_doc_url=doc_url,
                github_issue_url=github_issue_url,
                selected_ai_models=selected_models,
                system_architecture_summary=architecture_design,
                security_compliance_summary=compliance_plan,
                status="success"
            )

        except Exception as e:
            logger.error("Error during PersonaScriptArchitectureAgent execution", exc_info=True)
            return ArchitectureOutputs(
                miro_diagram_url="",
                security_plan_doc_url="",
                github_issue_url="",
                selected_ai_models=[],
                system_architecture_summary={},
                security_compliance_summary={},
                status="error",
                error_message=str(e)
            )

    def _parse_requirements(self, inputs: ArchitectureInputs) -> Dict[str, Any]:
        """Step 1: Parse functional and non-functional needs from requirements and value proposition."""
        return {
            "functional_requirements": [
                "Hyper-personalized B2B content generation across multi-stage funnels",
                "High-volume batch copy production with dynamic persona injection",
                "Real-time brand guideline adherence auditing and tone enforcement",
                "Multi-channel export (Email, Blog, Landing Pages, Social, Ads)"
            ],
            "non_functional_requirements": {
                "latency": "< 15s generation latency, < 2s API throughput response",
                "scalability": "Horizontal auto-scaling to handle peak batch volumes (> 100k requests/day)",
                "availability": "99.9% uptime SLA across compute and API services",
                "security": "End-to-end KMS encryption, zero LLM data retention, SOC 2 & GDPR compliance",
                "modularity": "Decoupled AI orchestration layer with multi-provider fallback"
            },
            "compliance_targets": inputs.compliance_standards,
            "existing_infra": inputs.existing_infrastructure or "Greenfield / AWS Cloud Infrastructure"
        }

    def _evaluate_ai_models(self, parsed_needs: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Step 2: Research and evaluate suitable AI models for hyper-personalized, high-volume generation."""
        return [
            {
                "tier": "Primary Orchestration / Long-form Personalization",
                "model_name": "Anthropic Claude 3.5 Sonnet",
                "provider": "Anthropic / AWS Bedrock",
                "role": "Complex persona-driven content generation, tone compliance auditing, and contextual reasoning",
                "latency_p95": "3.2s",
                "cost_per_1k_tokens": "$0.003 Input / $0.015 Output",
                "key_strengths": "Superior brand voice adherence, nuanced B2B tone understanding, large 200k context window"
            },
            {
                "tier": "High-Volume Batch Production",
                "model_name": "OpenAI GPT-4o / GPT-4o-mini",
                "provider": "OpenAI API",
                "role": "High-speed batch variant generation, short-form email/ad copy, and structured JSON parsing",
                "latency_p95": "1.1s",
                "cost_per_1k_tokens": "$0.00015 Input / $0.0006 Output (mini)",
                "key_strengths": "Sub-second response time, low cost per request, excellent JSON mode consistency"
            },
            {
                "tier": "Custom Fine-Tuned Proprietary Domain Model",
                "model_name": "PersonaScript-Llama-3-8B-Instruct",
                "provider": "AWS SageMaker Endpoints (Hugging Face / vLLM)",
                "role": "Proprietary brand guideline auditing and domain-specific B2B SaaS messaging fine-tuned on custom datasets",
                "latency_p95": "0.8s",
                "cost_per_1k_tokens": "Fixed GPU instance cost (ml.g5.2xlarge)",
                "key_strengths": "Complete data isolation, deterministic brand compliance scoring, zero external API latency dependencies"
            }
        ]

    def _design_aws_architecture(
        self,
        parsed_needs: Dict[str, Any],
        selected_models: List[Dict[str, Any]]
    ) -> Dict[str, Any]:
        """Step 3: Design high-level system architecture using AWS components."""
        return {
            "tier_1_edge_networking": {
                "components": ["AWS CloudFront", "AWS Route 53", "AWS WAF (Web Application Firewall)"],
                "purpose": "Global DDoS protection, SSL/TLS termination, and edge caching for static assets and web applications."
            },
            "tier_2_api_compute": {
                "components": ["Amazon API Gateway", "AWS EKS (Elastic Kubernetes Service)", "AWS Lambda"],
                "purpose": "REST API routing, serverless async task invocation, and containerized scalable microservices for content generation pipelines."
            },
            "tier_3_ai_orchestration": {
                "components": ["AWS Bedrock", "AWS SageMaker Endpoints", "LangChain / LlamaIndex Middleware"],
                "purpose": "Unified model proxy layer with fallback handling, prompt template injection, and proprietary Llama-3 model endpoint hosting."
            },
            "tier_4_data_caching_queues": {
                "components": ["Amazon ElastiCache for Redis", "Amazon SQS (Simple Queue Service)", "Amazon Kinesis Data Streams"],
                "purpose": "In-memory caching for brand guidelines/personas, decoupled message queuing for high-volume batch generation tasks."
            },
            "tier_5_storage_database": {
                "components": ["Amazon Aurora PostgreSQL (Serverless v2)", "Amazon DynamoDB", "Amazon S3"],
                "purpose": "Relational data for users/tenants, high-speed NoSQL for persona profiles, S3 bucket storage for exported batch zip artifacts."
            },
            "tier_6_security_observability": {
                "components": ["AWS KMS (Key Management Service)", "AWS IAM (Identity & Access Management)", "AWS CloudTrail", "Amazon CloudWatch"],
                "purpose": "Customer Managed KMS keys for envelope encryption, strict IAM role-based policies, audit trail logging, and metric alarms."
            }
        }

    def _develop_security_protocols(self) -> Dict[str, Any]:
        """Step 4: Develop comprehensive data security protocols."""
        return {
            "encryption_strategy": {
                "data_at_rest": "AES-256 encryption via AWS KMS with Customer Managed Keys (CMK) across S3, Aurora, DynamoDB, and ElastiCache.",
                "data_in_transit": "TLS 1.3 mandatory across all public endpoints and internal microservice-to-microservice traffic (mTLS via Istio Service Mesh)."
            },
            "access_control": {
                "iam_rbac": "Strict Principle of Least Privilege using AWS IAM Roles for Service Accounts (IRSA) and Okta/OAuth2 SAML SSO for enterprise users.",
                "api_security": "JWT bearer tokens, API key validation, rate limiting via AWS WAF and API Gateway throttling tiers."
            },
            "data_retention_and_privacy": {
                "retention_policy": "Automated data lifecycle policies: transient generation caches expire in 24 hours; customer profile data deleted 30 days post-cancellation.",
                "zero_data_retention_llm": "Zero Data Retention (ZDR) enterprise agreements with OpenAI and Anthropic to guarantee prompt data is never used for model training."
            },
            "audit_and_monitoring": {
                "logging": "AWS CloudTrail immutable trail logging, centralized CloudWatch log analytics, real-time intrusion detection via AWS GuardDuty."
            }
        }

    def _outline_compliance_plan(
        self,
        compliance_standards: List[str],
        security_protocols: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Step 5: Outline detailed security compliance plan addressing GDPR and SOC 2."""
        return {
            "gdpr_compliance": {
                "right_to_be_forgotten": "Automated API endpoint (`DELETE /v1/user-data`) triggering multi-store purge across Aurora, DynamoDB, and S3.",
                "data_portability": "Automated export mechanism (`GET /v1/user-data/export`) generating encrypted ZIP with all stored personas, brand guidelines, and collateral.",
                "data_processing_agreement": "Standard DPA provided for all B2B customers specifying EU-US Data Privacy Framework adherence and sub-processor transparent disclosures."
            },
            "soc2_compliance": {
                "security": "Role-Based Access Control (RBAC), multi-factor authentication (MFA), continuous vulnerability scanning, automated CI/CD security linting.",
                "availability": "Multi-AZ infrastructure deployment, automated failover for Aurora/ElastiCache, 99.9% availability SLA target.",
                "confidentiality": "Data segregation using tenant isolation keys, KMS envelope encryption, confidential compute enclaves for AI model inference.",
                "privacy": "Zero LLM model training guarantees, granular privacy settings for user persona inputs, transparent privacy policy."
            },
            "implementation_roadmap": [
                "Phase 1: AWS KMS CMK key configuration & IAM least privilege lockdown",
                "Phase 2: Automated data purge APIs and Zero Data Retention LLM agreement verification",
                "Phase 3: SOC 2 Type II readiness audit preparation and continuous monitoring via Vanta/Drata",
                "Phase 4: Annual third-party penetration testing and ISO 27001 roadmap alignment"
            ]
        }

    def _create_miro_diagram(
        self,
        architecture_design: Dict[str, Any],
        selected_models: List[Dict[str, Any]],
        security_protocols: Dict[str, Any]
    ) -> str:
        """Step 6: Create system architecture diagram in Miro."""
        board_data = {
            "title": "PersonaScript System Architecture & Security Layers",
            "layers": architecture_design,
            "models": selected_models,
            "security": security_protocols
        }
        return self.miro_integration.create_board(board_data)

    def _generate_compliance_doc(
        self,
        compliance_plan: Dict[str, Any],
        security_protocols: Dict[str, Any]
    ) -> str:
        """Step 7: Generate comprehensive security compliance plan document in Google Docs."""
        content = f"""# PersonaScript Data Security Protocols & Compliance Plan

## 1. Executive Summary
This document establishes the official data security architecture, encryption standards, access control mechanisms, and regulatory compliance roadmap (GDPR & SOC 2 Type II) for PersonaScript's content generation platform.

---

## 2. Comprehensive Data Security Protocols

### 2.1 Encryption Strategy
- **Data at Rest**: {security_protocols['encryption_strategy']['data_at_rest']}
- **Data in Transit**: {security_protocols['encryption_strategy']['data_in_transit']}

### 2.2 Access Control & Authentication
- **Identity & Access Management**: {security_protocols['access_control']['iam_rbac']}
- **API Protection**: {security_protocols['access_control']['api_security']}

### 2.3 Data Retention & Zero Training Policy
- **Data Retention**: {security_protocols['data_retention_and_privacy']['retention_policy']}
- **AI Model Data Privacy**: {security_protocols['data_retention_and_privacy']['zero_data_retention_llm']}

### 2.4 Audit Logging & Intrusion Detection
- **Monitoring**: {security_protocols['audit_and_monitoring']['logging']}

---

## 3. Industry Compliance Frameworks

### 3.1 GDPR (General Data Protection Regulation)
- **Right to Erasure (Article 17)**: {compliance_plan['gdpr_compliance']['right_to_be_forgotten']}
- **Data Portability (Article 20)**: {compliance_plan['gdpr_compliance']['data_portability']}
- **Data Processing Agreements**: {compliance_plan['gdpr_compliance']['data_processing_agreement']}

### 3.2 SOC 2 Type II Trust Services Criteria
- **Security**: {compliance_plan['soc2_compliance']['security']}
- **Availability**: {compliance_plan['soc2_compliance']['availability']}
- **Confidentiality**: {compliance_plan['soc2_compliance']['confidentiality']}
- **Privacy**: {compliance_plan['soc2_compliance']['privacy']}

---

## 4. Implementation Roadmap
"""
        for step in compliance_plan["implementation_roadmap"]:
            content += f"- {step}\n"

        return self.google_docs_integration.create_document(
            title="PersonaScript Security Compliance Plan & Data Security Protocols",
            content=content
        )

    def _create_github_issue(
        self,
        inputs: ArchitectureInputs,
        miro_url: str,
        doc_url: str,
        selected_models: List[Dict[str, Any]],
        architecture_design: Dict[str, Any],
        security_protocols: Dict[str, Any],
        compliance_plan: Dict[str, Any]
    ) -> str:
        """Step 8: Construct detailed GitHub issue detailing architecture, AI models, security, and links."""
        title = "Finalized Technical System Architecture, AI Model Selection & Security Compliance Plan"

        models_str = ""
        for m in selected_models:
            models_str += f"- **{m['model_name']}** ({m['provider']})\n"
            models_str += f"  - *Role*: {m['role']}\n"
            models_str += f"  - *Latency / Cost*: {m['latency_p95']} / {m['cost_per_1k_tokens']}\n"
            models_str += f"  - *Key Strengths*: {m['key_strengths']}\n\n"

        arch_str = ""
        for tier, data in architecture_design.items():
            tier_name = tier.replace('_', ' ').title()
            arch_str += f"- **{tier_name}**: `{', '.join(data['components'])}`\n  - {data['purpose']}\n"

        body = f"""# PersonaScript Technical System Architecture & Security Compliance Plan

## Goal
Finalize the technical architecture design, AI model selection, and data security protocols for PersonaScript's hyper-personalized content generation platform.

## Inputs Provided
- **Business Requirements**: {inputs.business_requirements}
- **Value Proposition**: {inputs.value_proposition}
- **Existing Infrastructure**: {inputs.existing_infrastructure or 'Greenfield / AWS Cloud Infrastructure'}
- **Compliance Standards**: {', '.join(inputs.compliance_standards)}

---

## Key Output Artifacts & Deliverables

- 🎨 **Miro System Architecture Diagram**: [View Architecture Diagram in Miro]({miro_url})
- 📄 **Security Compliance Plan Document**: [View Security Compliance Plan in Google Docs]({doc_url})

---

## 🤖 AI Model Selection Evaluation
{models_str}

## 🏗️ High-Level AWS Architecture Design
{arch_str}

## 🔒 Data Security Protocols Summary
- **Encryption at Rest**: {security_protocols['encryption_strategy']['data_at_rest']}
- **Encryption in Transit**: {security_protocols['encryption_strategy']['data_in_transit']}
- **Access Control**: {security_protocols['access_control']['iam_rbac']}
- **Zero LLM Data Retention**: {security_protocols['data_retention_and_privacy']['zero_data_retention_llm']}

## 📜 Compliance Standards Alignment (GDPR & SOC 2)
- **GDPR Support**: Automated erasure (`DELETE /v1/user-data`), export tools, and formal DPA framework.
- **SOC 2 Type II Alignment**: Comprehensive controls across Security, Availability, Confidentiality, and Privacy criteria.

---
*Generated automatically by PersonaScriptArchitectureAgent on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')} UTC.*
"""

        return self.github_integration.create_issue(
            title=title,
            body=body,
            labels=["architecture", "security", "compliance", "ai-models"]
        )
