"""
FigmaPrototypeDesignerAgent - Main agent for designing high-fidelity UI/UX mockups,
interactive prototypes for key MVP workflows, and an accompanying design system on Figma.

This agent follows a 9-step execution plan:
1. Receive and parse input specifications (workflows, user stories, brand guidelines)
2. Analyze brand guidelines to identify visual elements and establish interaction patterns
3. Initialize or update Figma design system file (components, styles, variables)
4. Translate user stories into structured wireframes for each specified workflow
5. Develop high-fidelity UI mockups in Figma applying design system components
6. Create interactive prototypes with navigation flows and interactions
7. Consolidate individual workflow prototypes into a master interactive Figma prototype file
8. Generate a public shareable URL for the complete Figma design system file
9. Create a detailed GitHub issue summarizing goals, inputs, outputs, and design process
"""

import os
import logging
from typing import Dict, List, Optional, Any
from dataclasses import dataclass, field
from datetime import datetime, timezone

from ..integrations.figma_integration import FigmaIntegration
from ..integrations.github_integration import GitHubIntegration

logger = logging.getLogger(__name__)


@dataclass
class UserStoryRequirement:
    """Represents a detailed user story or requirement for a workflow."""

    id: str
    title: str
    description: str
    acceptance_criteria: List[str] = field(default_factory=list)


@dataclass
class MVPWorkflow:
    """Represents a key MVP workflow to be designed."""

    name: str  # e.g., 'create a campaign', 'ingest brand guidelines'
    description: str
    user_stories: List[UserStoryRequirement] = field(default_factory=list)


@dataclass
class BrandGuidelines:
    """Represents PersonaScript brand guidelines."""

    brand_name: str = "PersonaScript"
    colors: Dict[str, str] = field(default_factory=lambda: {
        "primary": "#4F46E5",     # PersonaScript Indigo
        "secondary": "#7C3AED",   # Electric Violet
        "neutral_dark": "#111827",# Charcoal Black
        "neutral_light": "#F9FAFB",# Warm White
        "accent": "#F59E0B"       # Vibrant Amber
    })
    typography: Dict[str, Any] = field(default_factory=lambda: {
        "primary_font": "Inter",
        "heading_font": "Plus Jakarta Sans",
        "base_size": "16px",
        "scale": ["12px", "14px", "16px", "20px", "24px", "32px", "48px"]
    })
    logo_assets: List[str] = field(default_factory=lambda: [
        "https://personascript.com/assets/logo-full.svg",
        "https://personascript.com/assets/logo-mark.svg"
    ])
    voice_and_tone: str = "Professional, authoritative, intelligent, empathetic, and innovative."


@dataclass
class FigmaAgentInputs:
    """Input data for FigmaPrototypeDesignerAgent."""

    workflows: List[MVPWorkflow]
    brand_guidelines: BrandGuidelines


@dataclass
class FigmaAgentOutputs:
    """Outputs generated by FigmaPrototypeDesignerAgent."""

    prototype_url: str
    design_system_url: str
    github_issue_url: str
    design_system_data: Dict[str, Any]
    workflow_mockups: List[Dict[str, Any]]
    execution_log: List[Dict[str, Any]]
    status: str = "success"
    error_message: Optional[str] = None


class FigmaPrototypeDesignerAgent:
    """
    Main agent class for designing high-fidelity UI/UX mockups, interactive prototypes,
    and a Figma design system based on key MVP workflows and brand guidelines.
    """

    def __init__(
        self,
        figma_api_token: Optional[str] = None,
        figma_file_key: Optional[str] = None,
        github_token: Optional[str] = None,
        github_repo: Optional[str] = None
    ):
        """
        Initialize FigmaPrototypeDesignerAgent.

        Args:
            figma_api_token: API token for Figma
            figma_file_key: Default target file key in Figma
            github_token: Personal access token for GitHub API
            github_repo: Target repository (format: "owner/repo")
        """
        self.figma = FigmaIntegration(api_token=figma_api_token, file_key=figma_file_key)
        self.github = GitHubIntegration(token=github_token, repo=github_repo)
        self.execution_log: List[Dict[str, Any]] = []

        logger.info("FigmaPrototypeDesignerAgent initialized")

    def _log_step(self, step_number: int, description: str, status: str = "started", data: Optional[Dict] = None):
        """Log execution step into execution_log."""
        entry = {
            "step": step_number,
            "description": description,
            "status": status,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "data": data or {}
        }
        self.execution_log.append(entry)
        logger.info(f"Step {step_number}: {description} - {status}")

    def execute(self, inputs: FigmaAgentInputs) -> FigmaAgentOutputs:
        """
        Execute the complete 9-step Figma prototyping and design workflow.

        Args:
            inputs: FigmaAgentInputs containing MVP workflows and brand guidelines

        Returns:
            FigmaAgentOutputs with URLs to Figma prototype, design system, and GitHub issue
        """
        logger.info("Starting FigmaPrototypeDesignerAgent execution")
        self.execution_log = []

        try:
            # Step 1: Receive and parse input specifications (Tool: Internal Parser)
            self._log_step(1, "Receive and parse input specifications")
            parsed_inputs = self._parse_inputs(inputs)
            self._log_step(1, "Receive and parse input specifications", "completed", {
                "workflow_count": len(parsed_inputs["workflows"])
            })

            # Step 2: Analyze PersonaScript brand guidelines (Tool: Internal AI/Analysis Engine)
            self._log_step(2, "Analyze PersonaScript brand guidelines")
            analyzed_brand = self._analyze_brand_guidelines(parsed_inputs["brand_guidelines"])
            self._log_step(2, "Analyze PersonaScript brand guidelines", "completed")

            # Step 3: Initialize or update Figma design system file (Tool: Figma API)
            self._log_step(3, "Initialize or update Figma design system file")
            design_system = self.figma.create_or_update_design_system(
                brand_guidelines=analyzed_brand
            )
            self._log_step(3, "Initialize or update Figma design system file", "completed", {
                "file_key": design_system.get("file_key")
            })

            # Step 4, 5, 6: Process each specified MVP workflow (wireframes -> high-fidelity -> prototype)
            workflow_prototypes = []
            workflow_mockups_list = []

            for workflow in parsed_inputs["workflows"]:
                wf_name = workflow["name"]
                stories = workflow["user_stories"]

                # Step 4: Translate user stories into wireframes (Tool: Internal AI Design Module)
                self._log_step(4, f"Translate user stories into wireframes for '{wf_name}'")
                wireframes = self.figma.create_wireframes(wf_name, stories)

                # Step 5: Develop high-fidelity UI mockups in Figma (Tool: Figma API)
                self._log_step(5, f"Develop high-fidelity UI mockups for '{wf_name}'")
                hifi_mockups = self.figma.create_high_fidelity_mockups(wf_name, wireframes, design_system)
                workflow_mockups_list.append(hifi_mockups)

                # Step 6: Create interactive prototype navigation flows (Tool: Figma API)
                self._log_step(6, f"Create interactive prototype flows for '{wf_name}'")
                wf_proto = self.figma.create_interactive_prototype(wf_name, hifi_mockups)
                workflow_prototypes.append(wf_proto)

            # Step 7: Consolidate workflow prototypes into master interactive Figma prototype (Tool: Figma API)
            self._log_step(7, "Consolidate prototypes into master interactive Figma prototype")
            master_proto = self.figma.consolidate_master_prototype(workflow_prototypes)
            prototype_url = master_proto["master_url"]
            self._log_step(7, "Consolidate prototypes into master interactive Figma prototype", "completed", {
                "prototype_url": prototype_url
            })

            # Step 8: Generate public shareable URL for complete Figma design system file (Tool: Figma API)
            self._log_step(8, "Generate public shareable URL for design system file")
            design_system_url = self.figma.get_design_system_url(design_system)
            self._log_step(8, "Generate public shareable URL for design system file", "completed", {
                "design_system_url": design_system_url
            })

            # Step 9: Create a detailed GitHub issue (Tool: GitHub API)
            self._log_step(9, "Create detailed GitHub issue")
            github_issue_url = self._create_github_issue(
                inputs=parsed_inputs,
                analyzed_brand=analyzed_brand,
                design_system=design_system,
                design_system_url=design_system_url,
                workflow_mockups=workflow_mockups_list,
                prototype_url=prototype_url
            )
            self._log_step(9, "Create detailed GitHub issue", "completed", {
                "github_issue_url": github_issue_url
            })

            logger.info("FigmaPrototypeDesignerAgent execution completed successfully")
            return FigmaAgentOutputs(
                prototype_url=prototype_url,
                design_system_url=design_system_url,
                github_issue_url=github_issue_url,
                design_system_data=design_system,
                workflow_mockups=workflow_mockups_list,
                execution_log=self.execution_log,
                status="success"
            )

        except Exception as e:
            logger.error("Error during FigmaPrototypeDesignerAgent execution", exc_info=True)
            return FigmaAgentOutputs(
                prototype_url="",
                design_system_url="",
                github_issue_url="",
                design_system_data={},
                workflow_mockups=[],
                execution_log=self.execution_log,
                status="error",
                error_message=str(e)
            )

    def _parse_inputs(self, inputs: FigmaAgentInputs) -> Dict[str, Any]:
        """Step 1: Receive and parse input specifications."""
        logger.info("Step 1: Parsing input specifications")
        parsed_workflows = []

        for wf in inputs.workflows:
            stories = []
            for s in wf.user_stories:
                stories.append({
                    "id": s.id,
                    "title": s.title,
                    "description": s.description,
                    "acceptance_criteria": s.acceptance_criteria
                })
            parsed_workflows.append({
                "name": wf.name,
                "description": wf.description,
                "user_stories": stories
            })

        return {
            "workflows": parsed_workflows,
            "brand_guidelines": {
                "brand_name": inputs.brand_guidelines.brand_name,
                "colors": inputs.brand_guidelines.colors,
                "typography": inputs.brand_guidelines.typography,
                "logo_assets": inputs.brand_guidelines.logo_assets,
                "voice_and_tone": inputs.brand_guidelines.voice_and_tone
            }
        }

    def _analyze_brand_guidelines(self, brand_guidelines: Dict[str, Any]) -> Dict[str, Any]:
        """Step 2: Analyze PersonaScript brand guidelines to identify core visual elements and interaction patterns."""
        logger.info("Step 2: Analyzing brand guidelines and interaction patterns")
        colors = brand_guidelines.get("colors", {})
        typography = brand_guidelines.get("typography", {})

        return {
            "brand_name": brand_guidelines.get("brand_name", "PersonaScript"),
            "colors": {
                "primary": colors.get("primary", "#4F46E5"),
                "secondary": colors.get("secondary", "#7C3AED"),
                "neutral_dark": colors.get("neutral_dark", "#111827"),
                "neutral_light": colors.get("neutral_light", "#F9FAFB"),
                "accent": colors.get("accent", "#F59E0B")
            },
            "typography": {
                "primary_font": typography.get("primary_font", "Inter"),
                "heading_font": typography.get("heading_font", "Plus Jakarta Sans"),
                "base_size": typography.get("base_size", "16px"),
                "scale": typography.get("scale", ["12px", "14px", "16px", "20px", "24px", "32px", "48px"])
            },
            "spacing_grid": "8px base grid (8px, 16px, 24px, 32px, 48px, 64px)",
            "iconography": "Feather / Lucide icon set (24px line icons, 2px stroke weight)",
            "interaction_patterns": [
                "Hover feedback on primary buttons with 150ms ease-in-out transition",
                "Focus outline rings matching primary color for accessible navigation",
                "Slide-over drawers for secondary details and brand rule editing",
                "Modal overlays for high-consequence user actions and confirm steps",
                "Progress indicators and skeleton loaders during AI content generation"
            ],
            "voice_and_tone": brand_guidelines.get("voice_and_tone", "")
        }

    def _create_github_issue(
        self,
        inputs: Dict[str, Any],
        analyzed_brand: Dict[str, Any],
        design_system: Dict[str, Any],
        design_system_url: str,
        workflow_mockups: List[Dict[str, Any]],
        prototype_url: str
    ) -> str:
        """Step 9: Create a detailed GitHub issue summarizing goal, inputs, outputs, and design process."""
        title = f"PersonaScript Figma UI/UX Mockups & Interactive Prototype - Completed"

        workflow_names = [wf["name"] for wf in inputs["workflows"]]
        wf_list_str = "\n".join([f"- **{wf['name']}**: {wf['description']}" for wf in inputs["workflows"]])

        mockup_summaries = []
        for mockup in workflow_mockups:
            screens = len(mockup.get("screens", []))
            mockup_summaries.append(f"- **{mockup['workflow_name']}**: {screens} high-fidelity screens created ([Mockup File]({mockup['url']}))")
        mockup_str = "\n".join(mockup_summaries)

        body = f"""# PersonaScript Figma Design Project Summary

## Goal
Design high-fidelity UI/UX mockups, interactive prototypes for key MVP workflows, and an accompanying design system on Figma aligned with PersonaScript brand guidelines.

## Processed Inputs
- **MVP Workflows**:
{wf_list_str}
- **Brand Palette**:
  - Primary: `{analyzed_brand['colors']['primary']}`
  - Secondary: `{analyzed_brand['colors']['secondary']}`
  - Neutral Dark: `{analyzed_brand['colors']['neutral_dark']}`
  - Neutral Light: `{analyzed_brand['colors']['neutral_light']}`
  - Accent: `{analyzed_brand['colors']['accent']}`
- **Typography**: `{analyzed_brand['typography']['heading_font']}` (Headings) / `{analyzed_brand['typography']['primary_font']}` (Body)
- **Voice & Tone**: "{analyzed_brand['voice_and_tone']}"

## Generated Design Deliverables & URLs

- 🎨 **Figma Design System URL**: [PersonaScript Design System]({design_system_url})
- 🚀 **Interactive Master Prototype URL**: [PersonaScript Master Interactive Prototype]({prototype_url})

### High-Fidelity UI Mockups by Workflow
{mockup_str}

## Overview of Design Process & Execution
1. 📥 **Parsed Input Specifications**: Extracted MVP workflows (`{", ".join(workflow_names)}`) and detailed user stories.
2. 🎨 **Analyzed Brand Guidelines**: Defined core visual tokens (colors, typography, spacing scale, iconography, interaction rules).
3. 📐 **Built Figma Design System**: Structured reusable UI components (Buttons, Inputs, Cards, Sidebar) and global text/color styles.
4. 📝 **Created Wireframes**: Translated requirements and user stories into low-fidelity structural layouts.
5. 🖼️ **Developed High-Fidelity Mockups**: Applied design system components to deliver brand-aligned pixel-perfect screens.
6. 🔗 **Configured Prototype Interactions**: Defined transitions, button clicks, state changes, and smart-animate flows.
7. 🌐 **Consolidated Master Prototype**: Merged individual workflow interactive flows into a single shareable prototype.
8. 🔗 **Generated Public URLs**: Produced public shareable links for both master prototype and design system.
9. 📝 **Documented in GitHub**: Created this issue to establish clear design documentation and engineering traceability.

---
*Generated automatically by PersonaScript FigmaPrototypeDesignerAgent on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')} UTC.*
"""

        github_url = self.github.create_issue(
            title=title,
            body=body,
            labels=["design-system", "figma", "ui-ux", "mvp-prototype"]
        )
        return github_url
