"""
MarTechPartnershipScoutAgent - Main agent for scouting strategic partnership opportunities.

This agent:
1. Ingests PersonaScript's Value Proposition & Partnership Criteria
2. Uses LinkedIn searches to find tech providers/associations
3. Explores PartnerStack marketplace for integrations/complementary services
4. Analyzes compatibility (audience, tech stack, reach, strategic benefit)
5. Prioritizes/filters the best leads
6. Drafts preliminary partnership concepts and stores in Notion
7. Compiles a comprehensive report in Notion
8. Submits summary to GitHub issues
"""

import logging
from typing import Dict, List, Optional, Any
from dataclasses import dataclass, field

from ..integrations.linkedin_integration import LinkedInIntegration
from ..integrations.partnerstack_integration import PartnerStackIntegration
from ..integrations.notion_integration import NotionPartnershipIntegration
from ..integrations.github_integration import GitHubIntegration

logger = logging.getLogger(__name__)


@dataclass
class PartnershipCriteria:
    """Predefined partnership criteria parameters."""
    target_audiences: List[str] = field(default_factory=lambda: [
        "B2B SaaS Marketing Teams", "Demand Generation", "Content Marketers", "Growth Marketing"
    ])
    tech_stacks: List[str] = field(default_factory=lambda: [
        "HubSpot", "Marketo", "ActiveCampaign", "Zapier", "Salesforce"
    ])
    min_market_reach: str = "growth stage or established"


@dataclass
class PartnershipLead:
    """Represents a potential partner found during scouting."""
    name: str
    type: str  # Technology Provider, Industry Association, etc.
    source: str  # LinkedIn, PartnerStack, etc.
    description: str
    target_audience: str
    tech_stack: List[str]
    market_reach: str
    source_url: str
    compatibility_score: float = 0.0
    rationale: str = ""
    is_high_priority: bool = False


@dataclass
class PartnershipProposal:
    """Draft outline for a potential partnership proposal."""
    lead_name: str
    collaboration_areas: List[str]
    value_exchange: str
    integration_possibilities: List[str]
    notion_url: Optional[str] = None


@dataclass
class ScoutAgentInputs:
    """Inputs to the scout agent."""
    value_proposition: str
    criteria: PartnershipCriteria
    linkedin_credentials: Optional[Dict[str, Any]] = None
    partnerstack_api_key: Optional[str] = None
    notion_api_key: Optional[str] = None
    notion_database_id: Optional[str] = None
    github_token: Optional[str] = None
    github_repo: Optional[str] = "groupthinking/personascript"


@dataclass
class ScoutAgentOutputs:
    """Outputs generated by the scout agent."""
    leads: List[PartnershipLead]
    proposals: List[PartnershipProposal]
    comprehensive_report_url: str
    github_issue_url: str


class MarTechPartnershipScoutAgent:
    """
    Agent designed to identify, evaluate, and draft proposals for strategic marketing
    technology partnerships.
    """

    def __init__(
        self,
        linkedin_credentials: Optional[Dict[str, Any]] = None,
        partnerstack_api_key: Optional[str] = None,
        notion_api_key: Optional[str] = None,
        notion_database_id: Optional[str] = None,
        github_token: Optional[str] = None,
        github_repo: Optional[str] = None
    ):
        self.linkedin_integration = LinkedInIntegration(credentials=linkedin_credentials)
        self.partnerstack_integration = PartnerStackIntegration(api_key=partnerstack_api_key)
        self.notion_integration = NotionPartnershipIntegration(
            api_key=notion_api_key, database_id=notion_database_id
        )
        self.github_integration = GitHubIntegration(token=github_token, repo=github_repo)
        logger.info("MarTechPartnershipScoutAgent initialized")

    def execute(self, inputs: ScoutAgentInputs) -> ScoutAgentOutputs:
        """
        Execute the full partnership scouting and proposal generation workflow.
        """
        logger.info("Starting MarTech Partnership Scout workflow")

        # Step 1: Ingest and analyze value proposition and criteria
        criteria_analysis = self._ingest_parameters(inputs.value_proposition, inputs.criteria)

        # Step 2: Utilise LinkedIn to find marketing technology providers and industry associations
        linkedin_results = self._search_linkedin(criteria_analysis)

        # Step 3: Explore PartnerStack for complementary programs or services
        partnerstack_results = self._search_partnerstack(criteria_analysis)

        # Step 4: Perform preliminary analysis of identified entities
        all_leads = self._analyze_leads(linkedin_results, partnerstack_results, inputs.value_proposition, inputs.criteria)

        # Step 5: Filter and prioritize leads
        prioritized_leads = self._prioritize_leads(all_leads)

        # Step 6: Draft preliminary partnership proposals for high priority leads and store in Notion
        proposals = self._draft_proposals_in_notion(prioritized_leads)

        # Step 7: Compile comprehensive report in Notion
        report_url = self._compile_report_in_notion(prioritized_leads, proposals, inputs.value_proposition)

        # Step 8: Create GitHub issue summarizing goal, inputs, outputs, execution plan & report URL
        github_issue_url = self._create_github_issue(inputs, prioritized_leads, proposals, report_url)

        return ScoutAgentOutputs(
            leads=prioritized_leads,
            proposals=proposals,
            comprehensive_report_url=report_url,
            github_issue_url=github_issue_url
        )

    def _ingest_parameters(self, value_prop: str, criteria: PartnershipCriteria) -> Dict[str, Any]:
        """Step 1: Understand the value proposition and predefined partnership criteria."""
        logger.info("Step 1: Ingesting and analyzing value proposition and criteria")
        return {
            "value_prop_summary": value_prop,
            "keywords": ["martech", "marketing automation", "B2B SaaS marketing"] + criteria.tech_stacks + criteria.target_audiences,
            "target_audiences": criteria.target_audiences,
            "tech_stacks": criteria.tech_stacks
        }

    def _search_linkedin(self, criteria_analysis: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Step 2: Utilize LinkedIn's search capabilities to find matching entities."""
        logger.info("Step 2: Utilizing LinkedIn search capabilities")
        keywords = criteria_analysis["keywords"][:5]  # use top 5 keywords
        return self.linkedin_integration.search_companies_and_associations(keywords=keywords)

    def _search_partnerstack(self, criteria_analysis: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Step 3: Search PartnerStack for complementary programs/integrations."""
        logger.info("Step 3: Exploring PartnerStack ecosystem")
        keywords = criteria_analysis["keywords"][:3]
        return self.partnerstack_integration.search_marketplace(keywords=keywords)

    def _analyze_leads(
        self,
        linkedin_results: List[Dict[str, Any]],
        partnerstack_results: List[Dict[str, Any]],
        value_prop: str,
        criteria: PartnershipCriteria
    ) -> List[PartnershipLead]:
        """Step 4: Perform a preliminary compatibility analysis on all leads."""
        logger.info("Step 4: Performing preliminary compatibility analysis")
        leads = []

        # Process LinkedIn entities
        for ent in linkedin_results:
            compat_score, rationale = self._calculate_compatibility(ent, criteria, value_prop)
            leads.append(
                PartnershipLead(
                    name=ent["name"],
                    type=ent["type"],
                    source="LinkedIn",
                    description=ent.get("description", ""),
                    target_audience=ent.get("target_audience", "General"),
                    tech_stack=ent.get("tech_stack", []),
                    market_reach=ent.get("market_reach", "Unknown"),
                    source_url=ent.get("linkedin_url", ""),
                    compatibility_score=compat_score,
                    rationale=rationale
                )
            )

        # Process PartnerStack entities
        for ent in partnerstack_results:
            compat_score, rationale = self._calculate_compatibility(ent, criteria, value_prop)
            leads.append(
                PartnershipLead(
                    name=ent["name"],
                    type=ent["type"],
                    source="PartnerStack",
                    description=ent.get("description", ""),
                    target_audience="B2B SaaS / Growth Marketing",
                    tech_stack=ent.get("integrations_supported", []),
                    market_reach="Global",
                    source_url=ent.get("partnerstack_program_url", ""),
                    compatibility_score=compat_score,
                    rationale=rationale
                )
            )

        return leads

    def _calculate_compatibility(self, ent: Dict[str, Any], criteria: PartnershipCriteria, value_prop: str) -> tuple[float, str]:
        """Helper to compute compatibility score and rationale."""
        score = 0.5  # base compatibility score
        matching_techs = []
        ent_description = ent.get("description", "").lower()
        ent_name = ent.get("name", "").lower()

        # Check tech stack compatibility
        for tech in criteria.tech_stacks:
            if tech.lower() in ent_description or tech.lower() in [t.lower() for t in ent.get("tech_stack", [])] or tech.lower() in [t.lower() for t in ent.get("integrations_supported", [])]:
                score += 0.15
                matching_techs.append(tech)

        # Check target audience compatibility
        audience_match = False
        for aud in criteria.target_audiences:
            if aud.lower() in ent_description or aud.lower() in ent.get("target_audience", "").lower():
                score += 0.1
                audience_match = True

        score = min(1.0, score)

        # Build detailed rationale
        tech_rationale = f"Supports overlapping technologies: {', '.join(matching_techs)}" if matching_techs else "No explicit tech stack overlap detected"
        audience_rationale = "Target audience highly aligns with PersonaScript." if audience_match else "Audience has moderate relevance."

        rationale = f"{ent['name']} ({ent['type']}) is a strong fit. {audience_rationale} {tech_rationale}."
        return score, rationale

    def _prioritize_leads(self, leads: List[PartnershipLead]) -> List[PartnershipLead]:
        """Step 5: Filter and prioritize leads."""
        logger.info("Step 5: Filtering and prioritizing partnership leads")
        # Sort by compatibility score descending
        sorted_leads = sorted(leads, key=lambda l: l.compatibility_score, reverse=True)

        # Mark top 3 as high priority (threshold of >0.6 score)
        for i, lead in enumerate(sorted_leads):
            if i < 3 and lead.compatibility_score >= 0.6:
                lead.is_high_priority = True

        return sorted_leads

    def _draft_proposals_in_notion(self, leads: List[PartnershipLead]) -> List[PartnershipProposal]:
        """Step 6: Draft proposals for high-priority leads and store in Notion."""
        logger.info("Step 6: Drafting partnership proposals in Notion")
        proposals = []

        high_priority_leads = [l for l in leads if l.is_high_priority]
        for lead in high_priority_leads:
            # Create a structured proposal
            collaboration_areas = [
                f"Direct API Integration with PersonaScript to enable rapid content creation inside {lead.name}",
                f"Joint marketing webinars or co-authored guides targeting {lead.target_audience}",
                "Incentivized affiliate or referral programs via PartnerStack"
            ]
            value_exchange = (
                f"PersonaScript helps {lead.name} customers automate high-quality, persona-aligned "
                f"content, driving increased user retention and higher tool engagement. In exchange, "
                f"PersonaScript gains exposure to {lead.name}'s established market reach and customer base."
            )
            integration_possibilities = [
                f"Webhook notifications to trigger PersonaScript drafts directly from {lead.name} events.",
                f"Embedding PersonaScript creation modules within the {lead.name} ecosystem dashboard."
            ]

            # Construct markdown for Notion
            proposal_md = f"""# Partnership Proposal Outline: PersonaScript x {lead.name}

## 1. Overview
This proposal details a strategic partnership between PersonaScript (AI-powered hyper-personalized content creation platform) and {lead.name} ({lead.type}).

## 2. Strategic Objectives
- Accelerate lead conversion for B2B SaaS customers.
- Expand market reach for both platforms.
- Ensure cross-platform content brand consistency.

## 3. Collaboration Areas
{chr(10).join([f'- {area}' for area in collaboration_areas])}

## 4. Value Exchange
- **To {lead.name}:** {value_exchange}
- **To PersonaScript:** Access to {lead.market_reach} audience, native technology ecosystem.

## 5. Proposed Integration Possibilities
{chr(10).join([f'- {pos}' for pos in integration_possibilities])}
"""
            # Call Notion Integration
            notion_url = self.notion_integration.create_proposal_page(lead.name, proposal_md)

            proposals.append(
                PartnershipProposal(
                    lead_name=lead.name,
                    collaboration_areas=collaboration_areas,
                    value_exchange=value_exchange,
                    integration_possibilities=integration_possibilities,
                    notion_url=notion_url
                )
            )

        return proposals

    def _compile_report_in_notion(
        self,
        leads: List[PartnershipLead],
        proposals: List[PartnershipProposal],
        value_prop: str
    ) -> str:
        """Step 7: Compile a comprehensive report in Notion."""
        logger.info("Step 7: Compiling comprehensive report in Notion")

        proposals_dict = {p.lead_name: p.notion_url for p in proposals}

        leads_markdown = []
        for lead in leads:
            priority_tag = "🔴 **HIGH PRIORITY**" if lead.is_high_priority else "⚪ Medium/Low"
            proposal_link = f"[Draft Proposal in Notion]({proposals_dict[lead.name]})" if lead.name in proposals_dict else "N/A"
            leads_markdown.append(f"""### {lead.name} ({lead.type})
- **Priority:** {priority_tag}
- **Source:** {lead.source}
- **Compatibility Score:** {lead.compatibility_score:.2f}
- **Market Reach:** {lead.market_reach}
- **Rationale:** {lead.rationale}
- **Proposal Draft Link:** {proposal_link}
""")

        report_md = f"""# PersonaScript Strategic Partnership Scout Report

## Executive Summary
This report summarizes high-potential marketing technology partnerships and association opportunities mapped to accelerate PersonaScript's lead conversion and brand consistency value proposition.

## Value Proposition Refresher
"{value_prop}"

## Prioritized Partnership Leads
{chr(10).join(leads_markdown)}

## Next Steps
1. Review the generated proposal outlines in Notion.
2. Initiate outreach to high-priority leads ({', '.join([p.lead_name for p in proposals])}) via LinkedIn or PartnerStack connections.
3. Validate technical integrations and draft APIs.
"""

        report_url = self.notion_integration.create_comprehensive_report_page(
            "PersonaScript Partnership Scout Report", report_md
        )
        return report_url

    def _create_github_issue(
        self,
        inputs: ScoutAgentInputs,
        leads: List[PartnershipLead],
        proposals: List[PartnershipProposal],
        report_url: str
    ) -> str:
        """Step 8: Create a detailed GitHub issue summarizing the scouting run."""
        logger.info("Step 8: Creating GitHub issue summarizing results")

        high_priority_leads = [l for l in leads if l.is_high_priority]
        high_priority_str = ", ".join([l.name for l in high_priority_leads])

        body = f"""# MarTechPartnershipScoutAgent - Executive Summary

## Goal
Identify, evaluate, and initiate strategic partnership opportunities with complementary marketing technology providers or industry associations to accelerate lead conversion and brand consistency for PersonaScript.

## Inputs Ingested
- **PersonaScript's Value Proposition**: "{inputs.value_proposition}"
- **Partnership Criteria**:
  - Target Audiences: {', '.join(inputs.criteria.target_audiences)}
  - Tech Stack Compatibility: {', '.join(inputs.criteria.tech_stacks)}
  - Market Reach Requirement: {inputs.criteria.min_market_reach}
- **Access Credentials**: Provided and successfully mapped.

## Execution Plan Completed
1. ✅ **Ingest Context**: Analyzed value proposition and criteria parameters.
2. ✅ **LinkedIn Search**: Found potential marketing technology providers and industry associations.
3. ✅ **PartnerStack Search**: Explored existing partnership programs and complementary services.
4. ✅ **Preliminary Compatibility Analysis**: Assessed audience overlap, tech compatibility, and potential strategic benefit.
5. ✅ **Filter and Prioritize**: Filtered leads to identify high-priority opportunities.
6. ✅ **Draft Proposals**: Generated detailed partnership concepts and saved to Notion.
7. ✅ **Compile Comprehensive Report**: Built a central partnership registry and report in Notion.
8. ✅ **GitHub Issue Submission**: Created this tracking issue for human review.

## Key Scouting Results

### 📊 Comprehensive Scout Report
**URL:** {report_url}

### 🎯 High-Priority Leads & Draft Proposals
We identified **{len(high_priority_leads)}** high-priority strategic opportunities:
"""

        for proposal in proposals:
            body += f"\n- **{proposal.lead_name}** (Proposal Draft: {proposal.notion_url})\n"
            body += f"  - *Collaboration Area:* {proposal.collaboration_areas[0]}\n"
            body += f"  - *Value Exchange:* {proposal.value_exchange}\n"

        body += f"""
## All Scouting Candidates Identified ({len(leads)})
"""
        for lead in leads:
            p_tag = "🔥 [High Priority]" if lead.is_high_priority else ""
            body += f"- {lead.name} ({lead.type}) - Score: {lead.compatibility_score:.2f} {p_tag}\n"

        body += """
## Next Steps / Actions Required
- Human review of the Notion report and detailed proposal outlines.
- Update/approve proposal outlines with custom pricing or SLA terms.
- Initiate strategic outreach to priority leads.
"""

        issue_url = self.github_integration.create_issue(
            title="MarTech Strategic Partnership Scouting Results - Summary & Proposals",
            body=body,
            labels=["partnership-scouting", "completed"]
        )

        return issue_url
