"""
PersonaScript SalesGrowthStrategistAgent - Main agent for expanding the sales team,
refining the sales playbook, and establishing predictable revenue generation processes.

This agent executes a 7-step execution plan:
1. Collect and aggregate current sales performance data, call analytics, and market intelligence from Salesforce, Gong.io, and ZoomInfo.
2. Analyze collected data to identify sales process bottlenecks, playbook effectiveness, and team capacity gaps.
3. Refine and update the sales playbook incorporating data-driven best practices for prospecting, qualification, messaging, and objection handling.
4. Develop a detailed sales team expansion plan including organizational structure, role definitions, hiring profiles, and onboarding guidelines.
5. Formulate recommendations for optimizing Salesforce, Gong.io, and ZoomInfo utilization with focus on automation and insights.
6. Compile all strategy documents into a comprehensive report including MRR growth projections and sales efficiency metrics.
7. Create a detailed GitHub issue summarizing the goal, inputs, outputs, execution plan, and links to generated strategy blueprints.
"""

import logging
from typing import Dict, List, Optional, Any
from dataclasses import dataclass, field
from datetime import datetime, timezone

from ..integrations.salesforce_integration import SalesforceIntegration
from ..integrations.gong_integration import GongIntegration
from ..integrations.zoominfo_integration import ZoomInfoIntegration
from ..integrations.github_integration import GitHubIntegration

logger = logging.getLogger(__name__)


@dataclass
class AgentInputs:
    """Input parameters for the SalesGrowthStrategistAgent."""
    salesforce_api_key: Optional[str] = None
    salesforce_instance_url: Optional[str] = None
    salesforce_access_token: Optional[str] = None
    gong_access_key: Optional[str] = None
    gong_access_key_secret: Optional[str] = None
    zoominfo_username: Optional[str] = None
    zoominfo_password: Optional[str] = None
    zoominfo_client_id: Optional[str] = None
    existing_playbook: Optional[str] = None
    current_team_structure: Optional[Dict[str, Any]] = None
    icp_and_value_prop: Optional[str] = None
    target_mrr_growth_percent: float = 50.0  # Default 50% target growth projection


@dataclass
class AgentOutputs:
    """Output data generated by the SalesGrowthStrategistAgent."""
    refined_sales_playbook: str
    sales_team_expansion_plan: str
    tech_stack_recommendations: str
    revenue_impact_report: str
    github_issue_url: str
    execution_log: List[Dict[str, Any]] = field(default_factory=list)
    status: str = "success"
    error_message: Optional[str] = None


class SalesGrowthStrategistAgent:
    """
    Main agent class for refining the sales playbook, expanding the sales team,
    and establishing predictable revenue generation processes.
    """

    def __init__(
        self,
        salesforce_api_key: Optional[str] = None,
        salesforce_instance_url: Optional[str] = None,
        gong_access_key: Optional[str] = None,
        gong_access_key_secret: Optional[str] = None,
        zoominfo_username: Optional[str] = None,
        zoominfo_client_id: Optional[str] = None,
        github_token: Optional[str] = None,
        github_repo: Optional[str] = None
    ):
        """Initialize SalesGrowthStrategistAgent and external integrations."""
        self.salesforce = SalesforceIntegration(
            api_key=salesforce_api_key, instance_url=salesforce_instance_url
        )
        self.gong = GongIntegration(
            access_key=gong_access_key, access_key_secret=gong_access_key_secret
        )
        self.zoominfo = ZoomInfoIntegration(
            username=zoominfo_username, client_id=zoominfo_client_id
        )
        self.github = GitHubIntegration(
            token=github_token, repo=github_repo
        )
        self.execution_log: List[Dict[str, Any]] = []
        logger.info("SalesGrowthStrategistAgent initialized")

    def _log_step(self, step_number: int, description: str, status: str = "started", data: Optional[Dict] = None):
        """Record workflow execution step."""
        log_entry = {
            "step": step_number,
            "description": description,
            "status": status,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "data": data or {}
        }
        self.execution_log.append(log_entry)
        logger.info(f"Step {step_number}: {description} - {status}")

    def execute(self, inputs: Optional[AgentInputs] = None) -> AgentOutputs:
        """
        Execute the complete 7-step sales strategy and expansion workflow.

        Args:
            inputs: AgentInputs instance or None for defaults.

        Returns:
            AgentOutputs containing playbooks, expansion plans, recommendations, and GitHub issue URL.
        """
        logger.info("Starting SalesGrowthStrategistAgent execution")
        self.execution_log = []

        if inputs is None:
            inputs = AgentInputs()

        try:
            # Step 1: Collect and aggregate current sales performance data, call analytics, and market intelligence
            self._log_step(1, "Collect and aggregate data from Salesforce, Gong.io, and ZoomInfo")
            sf_metrics = self.salesforce.get_sales_performance_metrics()
            gong_analytics = self.gong.get_call_transcripts_and_analytics()
            zoominfo_intel = self.zoominfo.get_prospect_and_market_intelligence()
            self._log_step(1, "Collect and aggregate data from Salesforce, Gong.io, and ZoomInfo", "completed", {
                "mrr": sf_metrics.get("mrr"),
                "calls_analyzed": gong_analytics.get("total_calls_analyzed"),
                "addressable_accounts": zoominfo_intel.get("addressable_market_accounts_count")
            })

            # Step 2: Analyze collected data to identify bottlenecks, playbook effectiveness, and capacity gaps
            self._log_step(2, "Analyze data to identify bottlenecks, playbook effectiveness, and capacity gaps")
            analysis_data = self._analyze_sales_data(inputs, sf_metrics, gong_analytics, zoominfo_intel)
            self._log_step(2, "Analyze data to identify bottlenecks, playbook effectiveness, and capacity gaps", "completed")

            # Step 3: Refine and update the existing sales playbook based on data-driven insights
            self._log_step(3, "Refine and update existing sales playbook based on insights")
            refined_playbook = self._refine_sales_playbook(inputs, analysis_data)
            self._log_step(3, "Refine and update existing sales playbook based on insights", "completed")

            # Step 4: Develop a detailed sales team expansion plan
            self._log_step(4, "Develop detailed sales team expansion plan")
            expansion_plan = self._develop_expansion_plan(inputs, analysis_data)
            self._log_step(4, "Develop detailed sales team expansion plan", "completed")

            # Step 5: Formulate recommendations for optimizing Salesforce, Gong.io, and ZoomInfo utilization
            self._log_step(5, "Formulate recommendations for optimizing Salesforce, Gong.io, and ZoomInfo")
            tech_recommendations = self._formulate_tech_recommendations(inputs, analysis_data)
            self._log_step(5, "Formulate recommendations for optimizing Salesforce, Gong.io, and ZoomInfo", "completed")

            # Step 6: Compile strategy document with projected revenue growth and sales efficiency metrics
            self._log_step(6, "Compile strategy document and projected revenue impact report")
            revenue_report = self._compile_revenue_impact_report(inputs, sf_metrics, analysis_data)
            self._log_step(6, "Compile strategy document and projected revenue impact report", "completed")

            # Step 7: Create a detailed GitHub issue summarizing goal, inputs, outputs, execution plan, and links
            self._log_step(7, "Create comprehensive GitHub issue")
            github_issue_url = self._create_github_issue(
                inputs=inputs,
                playbook=refined_playbook,
                expansion_plan=expansion_plan,
                tech_recommendations=tech_recommendations,
                revenue_report=revenue_report,
                analysis_data=analysis_data
            )
            self._log_step(7, "Create comprehensive GitHub issue", "completed", {"github_issue_url": github_issue_url})

            logger.info("SalesGrowthStrategistAgent execution completed successfully")
            return AgentOutputs(
                refined_sales_playbook=refined_playbook,
                sales_team_expansion_plan=expansion_plan,
                tech_stack_recommendations=tech_recommendations,
                revenue_impact_report=revenue_report,
                github_issue_url=github_issue_url,
                execution_log=self.execution_log,
                status="success"
            )

        except Exception as e:
            logger.error("Error during SalesGrowthStrategistAgent execution", exc_info=True)
            return AgentOutputs(
                refined_sales_playbook="",
                sales_team_expansion_plan="",
                tech_stack_recommendations="",
                revenue_impact_report="",
                github_issue_url="",
                execution_log=self.execution_log,
                status="error",
                error_message=str(e)
            )

    def _analyze_sales_data(
        self,
        inputs: AgentInputs,
        sf_metrics: Dict[str, Any],
        gong_analytics: Dict[str, Any],
        zoominfo_intel: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Step 2: Analyze sales performance data, call transcripts, and market intelligence."""
        # Bottleneck 1: Cycle length & conversion rate
        cycle_days = sf_metrics.get("average_sales_cycle_days", 45.0)
        lead_conv = sf_metrics.get("lead_to_opportunity_rate", 0.12)
        win_rate = sf_metrics.get("opportunity_to_closed_won_rate", 0.22)

        bottlenecks = []
        if cycle_days > 30.0:
            bottlenecks.append(f"Extended Sales Cycle: Currently averaging {cycle_days} days. Slow discovery to demo progression.")
        if lead_conv < 0.15:
            bottlenecks.append(f"Sub-optimal Lead Qualification: Lead-to-Opportunity rate is {lead_conv*100:.1f}% (target: 15-20%).")
        if win_rate < 0.25:
            bottlenecks.append(f"Mid-Funnel Conversion Friction: Opportunity win rate is {win_rate*100:.1f}% (target: >25%).")

        # Rep Talk Ratios & Objections
        rep_talk = gong_analytics.get("average_talk_ratio", {}).get("rep_talk_percent", 62.0)
        top_objections = gong_analytics.get("top_objections", [])

        # Capacity Gaps
        open_opps = sf_metrics.get("open_opportunities_count", 48)
        current_team = inputs.current_team_structure or {"Account Executives": 2, "Sales Dev Reps (SDRs)": 1}
        ae_count = current_team.get("Account Executives", 2)
        opps_per_ae = open_opps / max(ae_count, 1)
        capacity_gap = opps_per_ae > 20.0  # Overloaded if >20 opps per AE

        return {
            "sf_metrics": sf_metrics,
            "gong_analytics": gong_analytics,
            "zoominfo_intel": zoominfo_intel,
            "identified_bottlenecks": bottlenecks,
            "rep_talk_percent": rep_talk,
            "top_objections": top_objections,
            "opps_per_ae": opps_per_ae,
            "capacity_gap_identified": capacity_gap,
            "addressable_accounts": zoominfo_intel.get("addressable_market_accounts_count", 4200)
        }

    def _refine_sales_playbook(self, inputs: AgentInputs, analysis: Dict[str, Any]) -> str:
        """Step 3: Refine and update the sales playbook."""
        icp_str = inputs.icp_and_value_prop or (
            "PersonaScript targets growth-stage B2B SaaS marketing teams (50-2000 employees) "
            "seeking to scale hyper-personalized content generation with full brand adherence."
        )

        objection_sections = []
        for obj in analysis.get("top_objections", []):
            name = obj.get("objection", "General Objection")
            freq = obj.get("frequency_percent", 0.0)
            phrases = ", ".join([f'"{p}"' for p in obj.get("common_phrases", [])])
            objection_sections.append(
                f"#### Objection: {name} (Frequency: {freq}%)\n"
                f"- **Common Prospect Expressions**: {phrases}\n"
                f"- **Recommended Pivot / Battlecard**: Focus on ROI benchmarks, automated brand governance score, and seamless API setup within 24 hours."
            )

        objections_markdown = "\n\n".join(objection_sections)

        playbook = f"""# Refined Sales Playbook - PersonaScript B2B SaaS Engine

## 1. Executive Summary & Ideal Customer Profile (ICP)
**Value Proposition & Target**: {icp_str}

### Target Buyer Personas & Decision Makers
- **VP of Growth Marketing**: Primary buyer, focused on scaling qualified pipeline and content throughput.
- **Head of Content Marketing**: Primary user champion, interested in workflow automation and brand guideline enforcement.
- **CMO / Executive Buyer**: Economic buyer, evaluates ROI, speed to market, and revenue impact.

---

## 2. Prospecting & Multichannel Outreach
- **Channel Mix**: Email sequences (40%), LinkedIn structured outreach (40%), Direct Phone/Video (20%).
- **Key Messaging Framework**:
  - Focus on pain point: Manual content creation bottleneck slowing lead acquisition.
  - Value driver: 10x content velocity while maintaining 100% brand voice consistency.

---

## 3. Qualification Criteria & Discovery Best Practices
- **Discovery Call Focus**: Rep talk time must be kept below 48% (current average: {analysis.get('rep_talk_percent', 62.0)}%).
- **Qualification Standards**:
  - *Situation*: Current content output volume and MarTech stack setup.
  - *Pain*: Specific bottlenecks in lead conversion and campaign deployment.
  - *Impact*: Revenue loss or delayed launch timelines due to content creation delays.
  - *Decision*: Budget authority and buying process.

---

## 4. Objection Handling & Competitor Battlecards
{objections_markdown}

---

## 5. Closing & Proposal Presentation
- Present ROI calculator demonstrating time saved per content campaign.
- Offer 14-day proof of concept (POC) with custom brand voice setup.
"""
        return playbook

    def _develop_expansion_plan(self, inputs: AgentInputs, analysis: Dict[str, Any]) -> str:
        """Step 4: Develop sales team expansion plan."""
        current_team = inputs.current_team_structure or {
            "Account Executives": 2,
            "Sales Development Representatives (SDRs)": 1,
            "Sales Leadership": 1
        }

        plan = f"""# Sales Team Expansion Plan & Organizational Structure

## 1. Current Capacity & Expansion Rationale
- **Current Team Structure**: {current_team}
- **Current Workload**: ~{analysis.get('opps_per_ae', 24):.1f} open opportunities per Account Executive.
- **Expansion Mandate**: Expand sales headcount to support target MRR growth, reduce sales cycle length, and maintain lead follow-up within 15 minutes.

---

## 2. Proposed Organizational Structure & Headcount Addition

### Phase 1: Inbound & Outbound SDR Capacity (Quarter 1)
- **Add 2 Sales Development Representatives (SDRs)**
  - *Role Definition*: Qualify inbound leads from marketing campaigns and execute outbound ZoomInfo intent-based cadences.
  - *Hiring Profile*: 1-3 years B2B SaaS prospecting experience, proficiency with Gong call review and CRM hygiene.

### Phase 2: Account Executive Scaling (Quarter 2)
- **Add 2 Senior Account Executives (AEs)**
  - *Role Definition*: Conduct deep discovery, manage product demonstrations, drive contract negotiations, and close new ARR/MRR.
  - *Hiring Profile*: 3-5 years closing experience in mid-market B2B SaaS, track record of quota attainment ($500k+ ARR).

### Phase 3: Sales Enablement & Customer Success (Quarter 2-3)
- **Add 1 Customer Success / Onboarding Specialist**
  - *Role Definition*: Ensure fast customer onboarding (<14 days), drive account adoption, and expand account expansion MRR.

---

## 3. Structured 30-60-90 Day Onboarding Guidelines
- **Days 1-30**: Intensive product mastery, brand guideline compliance training, shadowing top Gong recorded calls, CRM workflow practice.
- **Days 31-60**: First live discovery and demo calls with AE mentor oversight; meeting initial pipeline creation milestones.
- **Days 61-90**: Full quota assignment, independent pipeline management, monthly performance reviews against benchmark win rates.
"""
        return plan

    def _formulate_tech_recommendations(self, inputs: AgentInputs, analysis: Dict[str, Any]) -> str:
        """Step 5: Formulate tech stack optimization recommendations."""
        recommendations = f"""# Recommendations for Optimized Utilization of Salesforce, Gong.io, and ZoomInfo

## 1. Salesforce CRM Optimization & Automation
- **Automated Lead Routing**: Implement instant round-robin lead assignment based on account firmographics from ZoomInfo.
- **Pipeline Stage Gates**: Enforce required discovery fields (Pain Point, Timeline, Budget) before advancing opportunities past Stage 2.
- **Automated Opportunity Renewal & Expansion Alerts**: Configure automated tasks when account usage reaches 80% threshold.

---

## 2. Gong.io Conversational Intelligence & Coaching
- **Talk Ratio Alerts**: Automatically flag calls where AE talk time exceeds 50% for manager review.
- **Objection Tracker Customization**: Set up Gong trackers for "ROI proof", "Implementation timeline", and "Brand compliance".
- **Winning Call Library**: Curate a mandatory playlist of top closed-won calls for new hire onboarding.

---

## 3. ZoomInfo Market Intelligence & Intent Integration
- **Intent Signal Workflows**: Automatically push accounts searching for "AI Content Automation" directly into high-priority SDR cadences.
- **Form Complete Enrichment**: Enable real-time form enrichment to reduce web form fields to 3 while capturing full firmographic data.
- **Decision Maker Mapping**: Export contacts matching target titles (VP Growth, Head of Content) directly into Salesforce campaigns.
"""
        return recommendations

    def _compile_revenue_impact_report(
        self,
        inputs: AgentInputs,
        sf_metrics: Dict[str, Any],
        analysis: Dict[str, Any]
    ) -> str:
        """Step 6: Compile strategy document with projected revenue growth and sales efficiency metrics."""
        current_mrr = sf_metrics.get("mrr", 85000.0)
        target_growth_pct = inputs.target_mrr_growth_percent
        projected_mrr = current_mrr * (1.0 + (target_growth_pct / 100.0))
        net_mrr_addition = projected_mrr - current_mrr

        report = f"""# Projected Impact Report: MRR & Sales Efficiency Projections

## 1. Executive Revenue Summary
- **Current Monthly Recurring Revenue (MRR)**: ${current_mrr:,.2f}
- **Target MRR Growth Rate**: {target_growth_pct:.1f}%
- **Projected Target MRR**: ${projected_mrr:,.2f}
- **Net Projected MRR Addition**: +${net_mrr_addition:,.2f}

---

## 2. Expected Sales Efficiency Metrics Improvement

| Efficiency Metric | Current Baseline | Projected Target (Post-Expansion & Playbook Refinement) |
| :--- | :--- | :--- |
| **Lead-to-Opportunity Rate** | {sf_metrics.get('lead_to_opportunity_rate', 0.12)*100:.1f}% | **18.0%** (via ZoomInfo enrichment & qualification) |
| **Opportunity Win Rate** | {sf_metrics.get('opportunity_to_closed_won_rate', 0.22)*100:.1f}% | **28.0%** (via Gong objection handling & playbook) |
| **Average Sales Cycle** | {sf_metrics.get('average_sales_cycle_days', 45.0):.1f} Days | **30.0 Days** (via automated pipeline stage gating) |
| **Rep Talk Ratio** | {analysis.get('rep_talk_percent', 62.0):.1f}% | **< 48.0%** (via Gong call coaching) |
| **Quota Attainment Rate** | ~65% | **> 85%** |

---

## 3. Strategic Growth & Predictable Revenue Roadmap
- **Quarter 1**: Onboard 2 SDRs; establish ZoomInfo intent triggers; reduce average lead response time to <15 mins.
- **Quarter 2**: Onboard 2 AEs; launch refined Gong objection battlecards; achieve $110k+ MRR.
- **Quarter 3**: Scale to full quota performance; achieve target MRR of ${projected_mrr:,.2f}.
"""
        return report

    def _create_github_issue(
        self,
        inputs: AgentInputs,
        playbook: str,
        expansion_plan: str,
        tech_recommendations: str,
        revenue_report: str,
        analysis_data: Dict[str, Any]
    ) -> str:
        """Step 7: Create a detailed GitHub issue summarizing goal, inputs, outputs, execution plan, and strategy blueprints."""
        title = "PersonaScript Sales Growth Strategy, Expansion Plan & Refined Playbook"

        sf_mrr = analysis_data.get("sf_metrics", {}).get("mrr", 85000.0)

        body = f"""# PersonaScript Sales Growth Strategy & Expansion Blueprint

## Goal
To expand the sales team, refine the sales playbook, and establish predictable revenue generation processes for PersonaScript.

## Inputs Summary
- **Salesforce Metrics**: Baseline MRR: ${sf_mrr:,.2f}, Sales Cycle: {analysis_data.get('sf_metrics', {}).get('average_sales_cycle_days', 45)} days
- **Gong Call Analytics**: {analysis_data.get('gong_analytics', {}).get('total_calls_analyzed', 142)} calls analyzed, Rep Talk Ratio: {analysis_data.get('rep_talk_percent', 62)}%
- **ZoomInfo Intelligence**: {analysis_data.get('addressable_accounts', 4200)} target accounts identified across B2B SaaS
- **ICP & Value Prop**: {inputs.icp_and_value_prop or 'Default B2B SaaS Growth Marketing Focus'}

## Execution Plan & Completed Steps
1. 📊 **Collected and aggregated** sales performance metrics from Salesforce, Gong.io, and ZoomInfo APIs.
2. 🔍 **Analyzed sales data** to identify bottlenecks in sales cycle length, qualification rates, and rep talk ratios.
3. 📖 **Refined sales playbook** with structured prospecting, discovery questions, and targeted Gong objection battlecards.
4. 👥 **Developed sales team expansion plan** including 3-phase hiring schedule (SDRs, AEs, Customer Success) and 30-60-90 day onboarding.
5. ⚡ **Formulated MarTech optimization recommendations** for automated Salesforce routing, Gong call coaching, and ZoomInfo intent cadences.
6. 📈 **Compiled projected revenue impact report** demonstrating target MRR growth and key sales efficiency gains.
7. 🚀 **Created this GitHub issue** to document the complete strategic blueprint.

---

## Generated Strategy Blueprints & Reports

### 1. Refined Sales Playbook Overview
- Updated ICP alignment & decision maker targeting.
- Standardized discovery guidelines (target rep talk ratio <48%).
- Data-driven objection handling battlecards for Pricing, Implementation, and Security.

### 2. Sales Team Expansion Plan
- Proposed structure: Phase 1 (2 SDRs), Phase 2 (2 AEs), Phase 3 (1 CS Specialist).
- Structured 30-60-90 day onboarding roadmap.

### 3. Salesforce, Gong.io & ZoomInfo Tech Stack Recommendations
- Salesforce automated stage gates & round-robin routing.
- Gong automated talk-ratio alerts and winning call playlists.
- ZoomInfo real-time form enrichment and intent-based prospecting.

### 4. Projected MRR Impact & Revenue Efficiency
- Target MRR Growth: {inputs.target_mrr_growth_percent:.1f}%
- Win Rate Improvement Target: 22% -> 28%
- Sales Cycle Reduction Target: 45 Days -> 30 Days

---
*Blueprint generated automatically by SalesGrowthStrategistAgent.*
"""

        github_url = self.github.create_issue(
            title=title,
            body=body,
            labels=["sales-strategy", "playbook", "team-expansion", "revenue-growth"]
        )
        return github_url
